### ISSUE TITLE
Signature difference

### ISSUE THREAD

**Issue by readcash** [simpleledgerinc/grpc-bchrpc-web#3]
1. There is a difference between -web and -node calls in `getAddressUtxos`

`node` version has a signature of `getAddressUtxos({ address, includeMempool }...)`, whereas `web` version has this: `getAddressUtxos(address: string)` (not an object and lacks `includeMempool` parameter)

https://github.com/simpleledgerinc/grpc-bchrpc-node/blob/master/src/client.ts#L131
https://github.com/simpleledgerinc/grpc-bchrpc-web/blob/master/src/client.ts#L79

2. Also the same problem with `web`: `submitTransaction = function (txn)` expects base64 string, while `node` expects an object `{txnBuf: ..., txnHex: ..., txn: ...}`

**Comment by jcramer** [comment]
Closing this issue, it was resolved a while back.
